# Generated by Django 5.0.9 on 2024-09-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('transcribed_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
